#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kanata Arai
# SPDX-License-Identifier: BSD-3-Clause


import sys

ans = 0

for line in sys.stdin:
    line = line.strip()
    if line == "":
        continue  # 空行は読み飛ばす
    ans += float(line)

print(ans)

